tap "snyk/tap"
brew "bash-completion"
brew "btop"
brew "cmake"
brew "coreutils"
brew "gcc"
brew "gh"
brew "git"
brew "libomp", link: true
brew "pkgconf"
brew "pyenv"
brew "pyenv-virtualenv"
brew "saml2aws"
brew "wget"
brew "snyk/tap/snyk"
cask "keepassxc"
